@echo off
call check-git docs
call check-git eliud_core
call check-git eliud_generator
call check-git eliud_pkg_apps
call check-git eliud_pkg_chat
call check-git eliud_pkg_create
call check-git eliud_pkg_etc
call check-git eliud_pkg_feed
call check-git eliud_pkg_follow
call check-git eliud_pkg_fundamentals
call check-git eliud_pkg_medium
call check-git eliud_pkg_membership
call check-git eliud_pkg_notifications
call check-git eliud_pkg_pay
call check-git eliud_pkg_shop
call check-git eliud_pkg_text
call check-git eliud_pkg_wizards
call check-git eliud_pkg_workflow
call check-git eliud_stl_mona
call check-git firebase
call check-git juuwle
call check-git keys
call check-git minkey
