@echo off
call depends.cmd eliud_core
call depends.cmd eliud_core_helpers
call depends.cmd eliud_core_main
call depends.cmd eliud_core_model
call depends.cmd eliud_generator
call depends.cmd eliud_pkg_apps
call depends.cmd eliud_pkg_chat
call depends.cmd eliud_pkg_chat_model
call depends.cmd eliud_pkg_create
call depends.cmd eliud_pkg_create_model
call depends.cmd eliud_pkg_etc
call depends.cmd eliud_pkg_etc_model
call depends.cmd eliud_pkg_feed
call depends.cmd eliud_pkg_feed_model
call depends.cmd eliud_pkg_follow
call depends.cmd eliud_pkg_follow_model
call depends.cmd eliud_pkg_fundamentals
call depends.cmd eliud_pkg_fundamentals_model
call depends.cmd eliud_pkg_medium
call depends.cmd eliud_pkg_medium_model
call depends.cmd eliud_pkg_membership
call depends.cmd eliud_pkg_membership_model
call depends.cmd eliud_pkg_notifications
call depends.cmd eliud_pkg_notifications_model
call depends.cmd eliud_pkg_pay
call depends.cmd eliud_pkg_shop
call depends.cmd eliud_pkg_shop_model
call depends.cmd eliud_pkg_text
call depends.cmd eliud_pkg_text_model
call depends.cmd eliud_pkg_wizards
call depends.cmd eliud_pkg_workflow
call depends.cmd eliud_pkg_workflow_model
call depends.cmd eliud_stl_mona
call depends.cmd eliud_stl_mona_model
call depends.cmd juuwle
call depends.cmd minkey
