@echo off
call fix-format eliud_core %1
call fix-format eliud_core_helpers %1
call fix-format eliud_generator %1
call fix-format eliud_pkg_apps %1
call fix-format eliud_pkg_chat %1
call fix-format eliud_pkg_create %1
call fix-format eliud_pkg_etc %1
call fix-format eliud_pkg_feed %1
call fix-format eliud_pkg_follow %1
call fix-format eliud_pkg_fundamentals %1
call fix-format eliud_pkg_medium %1
call fix-format eliud_pkg_membership %1
call fix-format eliud_pkg_notifications %1
call fix-format eliud_pkg_pay %1
call fix-format eliud_pkg_shop %1
call fix-format eliud_pkg_text %1
call fix-format eliud_pkg_wizards %1
call fix-format eliud_pkg_workflow %1
call fix-format eliud_stl_mona %1
