@echo off
call toc.cmd eliud_core
call toc.cmd eliud_core_helpers
call toc.cmd eliud_core_main
call toc.cmd eliud_core_model
call toc.cmd eliud_generator
call toc.cmd eliud_pkg_apps
call toc.cmd eliud_pkg_chat
call toc.cmd eliud_pkg_chat_model
call toc.cmd eliud_pkg_create
call toc.cmd eliud_pkg_create_model
call toc.cmd eliud_pkg_etc
call toc.cmd eliud_pkg_etc_model
call toc.cmd eliud_pkg_feed
call toc.cmd eliud_pkg_feed_model
call toc.cmd eliud_pkg_follow
call toc.cmd eliud_pkg_follow_model
call toc.cmd eliud_pkg_fundamentals
call toc.cmd eliud_pkg_fundamentals_model
call toc.cmd eliud_pkg_medium
call toc.cmd eliud_pkg_medium_model
call toc.cmd eliud_pkg_membership
call toc.cmd eliud_pkg_membership_model
call toc.cmd eliud_pkg_notifications
call toc.cmd eliud_pkg_notifications_model
call toc.cmd eliud_pkg_pay
call toc.cmd eliud_pkg_shop
call toc.cmd eliud_pkg_shop_model
call toc.cmd eliud_pkg_text
call toc.cmd eliud_pkg_text_model
call toc.cmd eliud_pkg_wizards
call toc.cmd eliud_pkg_workflow
call toc.cmd eliud_pkg_workflow_model
call toc.cmd eliud_stl_mona
call toc.cmd eliud_stl_mona_model
